version: '3'

services:
  pulse-server:
    build: .
    ports:
      - "50051:50051"
    environment:
      - PULSE_PORT=50051
      - PULSE_TIMEOUT=30s
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 30s
      timeout: 10s
      retries: 3
